### ISSUE TITLE
Comment in demo.md appears to not be block comment?

### ISSUE THREAD

**Issue by bjornbm** [tomduck/pandoc-comments#1]
This looks like two line comments:

```
% The following lorem ipsum was obtained from the generator at
% https://lipsum.com/

…
```

Based on `README.md` saying that…

> Block comments are declared in markdown documents by using a percent sign (%) at the beginning of a paragraph.

…I assume the following should be equivalent to the example in `demo.md`?:

```
% The following lorem ipsum was obtained from the generator at
https://lipsum.com/

…
```
 
That is; the `%` is required only on the first line of the block comment (paragraph)?

**Comment by tomduck** [comment]
Yes, you are correct.  Only the first %-sign is needed.  Pandoc's abstract syntax tree does not have a Line type, so line-by-line processing isn't even possible.

I used a percent sign in the example for each line because it is visually appealing.  I do the same in all of my work.

Cheers, Tom.

**Comment by tomduck** [comment]
I added a note about this issue in the README.md.
