### ISSUE TITLE
Document how this interacts with metadata-blocks

### ISSUE THREAD

**Issue by bjornbm** [tomduck/pandoc-comments#2]
Will [meta-data blocks](https://pandoc.org/MANUAL.html#metadata-blocks) with `%` be kept or should one use [YAML meta-data blocks](https://pandoc.org/MANUAL.html#extension-yaml_metadata_block) instead?

**Comment by tomduck** [comment]
Ah, good point.  Comments are only stripped from the body of the document.  The YAML is unaffected.  I will revise the documentation accordingly.

**Comment by tomduck** [comment]
I added a note about this issue in the README.md.

**Comment by bjornbm** [comment]
Maybe I was unclear in my question, and maybe this is a non-issue due to pandoc taking care of this before it gets to your filter (I haven't tried it) but your answer still isn't clear to me. So to clarify my question: as you probably know you can start a pandoc input document with three lines such as:

```
% My Title
% Björn Buckwalter
% 2019-09-18
```

These will be recognized by pandoc used for the title, author, and date of a latex article for example. Will they still be recognized and used by pandoc (and not removed as comments)? I guess they will if you filter the AST and not the raw input but it would be nice to confirm.

(They alternative way of providing meta-data is with a YAML block.)

**Comment by tomduck** [comment]
I clarified the README.md by saying "Pandoc metadata blocks are not processed by this filter."  I tested this using the block you provided above and confirmed that this is the case.  As you guessed, pandoc-comments filters the AST.  Cheers, Tom.
